/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;


/**
 *
 * @author luole
 */
public class MainJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainJFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        registrationPanel = new javax.swing.JPanel();
        registrationLabel1 = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        firstNameTextfield = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        MaleRadioButton = new javax.swing.JRadioButton();
        FemaleRadioButton = new javax.swing.JRadioButton();
        submitButton = new javax.swing.JButton();
        firstNameLabel = new javax.swing.JLabel();
        emailLAbel = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registrationPanel.setBackground(new java.awt.Color(0, 255, 204));

        registrationLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registrationLabel1.setText("Profile Registration");

        lastNameLabel.setText("Last Name :");

        ageLabel.setText("Age:");

        genderLabel.setText("Gender");

        firstNameTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextfieldActionPerformed(evt);
            }
        });

        ageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextFieldActionPerformed(evt);
            }
        });

        genderButtonGroup.add(MaleRadioButton);
        MaleRadioButton.setText("Male");
        MaleRadioButton.setActionCommand(" Male");
        MaleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleRadioButtonActionPerformed(evt);
            }
        });

        genderButtonGroup.add(FemaleRadioButton);
        FemaleRadioButton.setText("Female");
        FemaleRadioButton.setActionCommand("Female");
        FemaleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleRadioButtonActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        firstNameLabel.setText("First Name :");

        emailLAbel.setText("Email:");

        phoneNumberLabel.setText("Phone Number:");

        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });

        phoneTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registrationPanelLayout = new javax.swing.GroupLayout(registrationPanel);
        registrationPanel.setLayout(registrationPanelLayout);
        registrationPanelLayout.setHorizontalGroup(
            registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationPanelLayout.createSequentialGroup()
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrationPanelLayout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(registrationLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registrationPanelLayout.createSequentialGroup()
                        .addContainerGap(82, Short.MAX_VALUE)
                        .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrationPanelLayout.createSequentialGroup()
                                .addComponent(firstNameLabel)
                                .addGap(120, 120, 120)
                                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(firstNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrationPanelLayout.createSequentialGroup()
                                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailLAbel)
                                    .addComponent(ageLabel)
                                    .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phoneNumberLabel)
                                    .addComponent(genderLabel))
                                .addGap(99, 99, 99)
                                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MaleRadioButton)
                                    .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ageTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                        .addComponent(phoneTextField)
                                        .addComponent(emailTextField)
                                        .addComponent(FemaleRadioButton))
                                    .addComponent(submitButton))))))
                .addContainerGap(306, Short.MAX_VALUE))
        );
        registrationPanelLayout.setVerticalGroup(
            registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(registrationLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageLabel))
                .addGap(18, 18, 18)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumberLabel))
                .addGap(18, 18, 18)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLAbel))
                .addGap(26, 26, 26)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLabel)
                    .addComponent(FemaleRadioButton))
                .addGap(34, 34, 34)
                .addComponent(MaleRadioButton)
                .addGap(30, 30, 30)
                .addComponent(submitButton)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registrationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registrationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextfieldActionPerformed

    private void ageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTextFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
    // TODO add your handling code here:
     try {
        // Declare Variables from user input
        String firstName;
        String lastName;
        int age;
        String gender;
        String email;
        String phoneNumber;
        
        // Extract and Store user data
        firstName = firstNameTextfield.getText();
        lastName = lastNameTextField.getText();
        age = Integer.parseInt(ageTextField.getText());
        email = emailTextField.getText();
        phoneNumber = phoneTextField.getText();
        
        // Get gender from radio button group
        if (genderButtonGroup.getSelection() != null) {
            gender = genderButtonGroup.getSelection().getActionCommand();
        } else {
            gender = null;
        }
        
        // Validate first name
        // Check if firstname is blank
        if (firstName.isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Invalid first name provided!", "Ooops!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //check first name only contains letter and space
        if (!firstName.matches("[a-zA-Z\\s]+")) {
            JOptionPane.showMessageDialog(rootPane, "First name can only contain letters and spaces!", "Ooops!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Validate last name
        // Check if lastname is blank
        if (lastName.isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Invalid last name provided!", "Ooops!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //check last name only contains letter and space
        if (!lastName.matches("[a-zA-Z\\s]+")) {
            JOptionPane.showMessageDialog(rootPane, "Last name can only contain letters and spaces!", "Ooops!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Validate age
        if (age <= 0) {
            JOptionPane.showMessageDialog(rootPane, "Age must be greater than 0!", "Ooops!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (age > 120) {
            JOptionPane.showMessageDialog(rootPane, "Invalid age provided! Must be 120 or younger.", "Ooops!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Validate gender selection
        if (gender == null) {
            JOptionPane.showMessageDialog(rootPane, "Please select a gender!", "Ooops!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Validate email
        if (email.isBlank() || !email.matches("^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$")) {
            JOptionPane.showMessageDialog(rootPane, "Invalid email address provided!", "Ooops!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Validate phone number
        String cleanPhone = phoneNumber.replaceAll("[\\s\\-\\(\\)]", "");
        if (phoneNumber.isBlank() || !cleanPhone.matches("\\d{10,15}")) {
            JOptionPane.showMessageDialog(rootPane, "Invalid phone number provided!", "Ooops!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Create success message
        String successMessage = "Registration Successful!\n\n" +
                               "First Name: " + firstName + "\n" +
                               "Last Name: " + lastName + "\n" +
                               "Age: " + age + "\n" +
                               "Gender: " + gender + "\n" +
                               "Email: " + email + "\n" +
                               "Phone: " + phoneNumber;
        
        JOptionPane.showMessageDialog(rootPane, successMessage, "Success!", JOptionPane.INFORMATION_MESSAGE);
        
        // Clear form after successful submission (optional)
        firstNameTextfield.setText("");
        lastNameTextField.setText("");
        ageTextField.setText("");
        emailTextField.setText("");
        phoneTextField.setText("");
        genderButtonGroup.clearSelection();
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(rootPane, "Invalid age provided! Please enter a valid number.", "Ooops!", JOptionPane.ERROR_MESSAGE);
    }  
     
     catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, "Something went wrong! Please try again.", "Ooops!", JOptionPane.ERROR_MESSAGE);
        // System.out.println("Error: " + e.getMessage());
    }
   

 
        
        
    }//GEN-LAST:event_submitButtonActionPerformed

    private void MaleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleRadioButtonActionPerformed

    private void FemaleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemaleRadioButtonActionPerformed

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void phoneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton FemaleRadioButton;
    private javax.swing.JRadioButton MaleRadioButton;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JLabel emailLAbel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextfield;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JLabel registrationLabel1;
    private javax.swing.JPanel registrationPanel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
